# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: enabled
dist: xenial
cache:
  - packages
  - ccache
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'

    packages:
#      - libprotobuf-dev
#      - protobuf-compiler
#      - libv8-3.14-dev
#      - libjq-dev
#      - libjson-c-dev
#      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - gdal-bin

matrix:
    include:
        - os: linux
          r: release
          dist: xenial # 16.04
          env:
           - BUILD_NAME=xenial_release
           - R_CODECOV=true
        - os: linux
          r: devel
          dist: xenial
        - os: linux
          r: oldrel
          dist: xenial
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true
          env:
           - BUILD_NAME=osx_release
           - R_CODECOV=true
          #- os: osx
          #r: devel
          #before_install: ''
          #disable_homebrew: true

after_success:
  - Rscript -e 'covr::codecov()'
