# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

matrix:
    allow_failures:
        -os: osx
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env: R_CODECOV=true

        - os: linux
          r: devel
          dist: trusty

        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true


dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libproj-dev libgdal-dev


r_github_packages:
  - jimhester/covr


after_success:
  - Rscript -e 'covr::codecov()'
