# https://raw.githubusercontent.com/mpadge/sftest/master/.travis.yml

language: r
warnings_are_errors: true
sudo: required
cache: packages

matrix:
    allow_failures:
        -os: osx
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env: R_CODECOV=true
        # precise fails because unmet deps in libgdal-dev can not be installed
        #- os: linux
        #  r: release
        #  dist: precise # 12.04
        - os: linux
          r: devel
          dist: trusty
        ## I can't see why this fails, but depsf and sftest work fine
#        - os: osx
#          r: release
#          before_install: ''
#          disable_homebrew: true

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
