# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

compiler: clang
sudo: enabled
dist: trusty
cache:
 packages
 apt: true
 directories:
  - $HOME/.ccache
  env:
   - BUILD_NAME=trusty_clang
   - DETAILS="optimized build, no libtool"

before_install:
  - cd
  - git clone https://github.com/OSGeo/gdal.git
  - cd gdal
  - cd
  ## put the /gdal and /autotest at this location
  - mv gdal gdal_go
  - mv gdal_go/gdal .
  - mv gdal_go/autotest .
  - ./gdal/ci/travis/${BUILD_NAME}/before_install.sh

install:
  - ./gdal/ci/travis/${BUILD_NAME}/install.sh
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  - Rscript -e 'covr::codecov()'

