# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages


# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: clang
      sudo: required
      dist: trusty
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      env:
        - BUILD_NAME=trusty_clang
        - DETAILS="optimized build, no libtool"

## afaict you really need all three scripts to run for this to work
## before_install.sh, install.sh, and script.sh
before_install:
  - cd
  - git clone https://github.com/OSGeo/gdal.git
  - cd gdal
  - cd
  ## put the /gdal and /autotest at this location
  - mv gdal gdal_go
  - mv gdal_go/gdal .
  - mv gdal_go/autotest .
  - ./gdal/ci/travis/${BUILD_NAME}/before_install.sh

install:
  - ./gdal/ci/travis/${BUILD_NAME}/install.sh
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *tar.gz

after_success:
    - Rscript -e 'covr::codecov()'

